export enum Color {
  Black = 'black',
  CharcoalGrey = '#333233',
  CourtGreen = '#00878B',
  Grass = '#6eb22c',
  Snot = '#b4b910',
  Pale = '#e7e5e5',
  GreyishBrown = '#4a4a4a',
  GreyishBrownTwo = '#585858',
  GreyishBrownThree = '#424242',
  Green = '#00C464',
  BrownishGrey = '#6f6f6f',
  Dark80 = '#17272a',
  Dark60 = '#000000',
  DarkerGrey = '#bbbbbb',
  DarkerGray = '#A39CAC',
  DarkerGray2 = '#2F2F2F',
  AlmostWhite = '#FEFEFE',
  BrownGrey = '#8e8e8e',
  VeryLightPink = '#dbdbdb',
  MediumGrey = '#6f6f6e',
  VeryLightPinkTwo = '#cccccc',
  UglyYellow = '#cccd01',
  LightGrey2 = '#9b9b9b',
  LightGrey3 = '#f2f2f2',
  OrangeyRed = '#fe3824',
  LightGreyBlue = '#b3bdc2',
  LightGrey = '#979797',
  OrangeyYellow = '#f5a623',
  Sea = '#349899',
  Shamrock = '#02b665',
  ShamrockGreen = '#01CD40',
  ShamrockGreenLight = '#ECFCF2',
  DeepSkyBlue = '#037aff',
  Gray = '#fefefe',
  TealGreen = '#249775',
  Transparent = 'transparent',
  White = 'white',
  SeaTwo = '#3c989b',
  BrownGreyTwo = '#9b9b9b',
  Cement = '#999998',
  VeryLightPinkFour = '#dadada',
  BrownishGreyTwo = '#686868',
  BrownGreyThree = '#aaaaaa',
  DarkSkyBlue = 'rgba(52, 170, 220, 0.35)',
  GreyishTeal = '#58b1ab',
  Pea = '#bab823',
  LightBurgundy = '#a62938',
  DarkGrey = '#303031',
  DarkestGray = '#404040',
  BlackTwo = '#1e1e1e',
  VeryLightPinkSix = '#e9e9e9',
  VeryLightPinkSeven = '#cecece',
  AquaMarine = '#52bbbf',
  GrayTheme = '#6C6C6C',
  Gray2Theme = '#AFAFAF',
  Gray3Theme = '#696D6F',
  Gray4Theme = '#f0f0f0',
  Gray5Theme = '#d8d8d8',
  Gray6Theme = '#eaeaea',
  Gray7Theme = '#c7c7cc',
  Primary = '#249775',
  Accent = '#3A979A',
  VomitGreen = '#CCCD01',
  White3 = '#AFEDDB',
  WhiteTransparent = '#FFFFFFCC',
  ClearGreen = '#97C7C9',
  White2 = '#AFEDDB',
  MustardYellow = '#B2992C',
  DeepBlue = '#248697',
  SkyBlue = '#007aff',
  SmoothBlack = 'rgba(31, 31, 31,1)',
  Orange = '#e1940d',
  Pink = '#fb4a68',
  Red = '#e02020',
  Yellow = '#f7b500',
  GrayAutocomplete = '#b5b5b5',
}

export const Palette = {
  Accent: Color.Accent,
  AlmostWhite: Color.AlmostWhite,
  AquaMarine: Color.AquaMarine,
  Black: Color.Black,
  BlackTwo: Color.BlackTwo,
  BrownGrey: Color.BrownGrey,
  BrownGreyThree: Color.BrownGreyThree,
  BrownGreyTwo: Color.BrownGreyTwo,
  BrownishGrey: Color.BrownishGrey,
  BrownishGreyTwo: Color.BrownishGreyTwo,
  Cement: Color.Cement,
  CharcoalGrey: Color.CharcoalGrey,
  ClearGreen: Color.ClearGreen,
  CourtGreen: Color.CourtGreen,
  Dark60: Color.Dark60,
  Dark80: Color.Dark80,
  DarkGrey: Color.DarkGrey,
  DarkSkyBlue: Color.DarkSkyBlue,
  DarkerGray: Color.DarkerGray,
  DarkerGray2: Color.DarkerGray2,
  DarkerGrey: Color.DarkerGrey,
  DarkestGray: Color.DarkestGray,
  DeepBlue: Color.DeepBlue,
  DeepSkyBlue: Color.DeepSkyBlue,
  Error: Color.OrangeyRed,
  Grass: Color.Grass,
  Gray: Color.Gray,
  Gray2Theme: Color.Gray2Theme,
  Gray3Theme: Color.Gray3Theme,
  Gray4Theme: Color.Gray4Theme,
  Gray5Theme: Color.Gray5Theme,
  Gray6Theme: Color.Gray6Theme,
  Gray7Theme: Color.Gray7Theme,
  GrayAutocomplete: Color.GrayAutocomplete,
  GrayTheme: Color.GrayTheme,
  Green: Color.Green,
  GreyishBrown: Color.GreyishBrown,
  GreyishBrownThree: Color.GreyishBrownThree,
  GreyishBrownTwo: Color.GreyishBrownTwo,
  GreyishTeal: Color.GreyishTeal,
  LightBurgundy: Color.LightBurgundy,
  LightGrey: Color.LightGrey,
  LightGrey2: Color.LightGrey2,
  LightGrey3: Color.LightGrey3,
  LightGreyBlue: Color.LightGreyBlue,
  MediumGray: Color.MediumGrey,
  MediumGrey: Color.MediumGrey,
  MustardYellow: Color.MustardYellow,
  Orange: Color.Orange,
  OrangeyRed: Color.OrangeyRed,
  OrangeyYellow: Color.OrangeyYellow,
  Pale: Color.Pale,
  Pea: Color.Pea,
  Pink: Color.Pink,
  Primary: Color.Primary,
  PrimaryDark: Color.Black,
  Red: Color.Red,
  Sea: Color.Sea,
  SeaTwo: Color.SeaTwo,
  Shamrock: Color.Shamrock,
  ShamrockGreen: Color.ShamrockGreen,
  ShamrockGreenLight: Color.ShamrockGreenLight,
  SkyBlue: Color.SkyBlue,
  SmoothBlack: Color.SmoothBlack,
  Snot: Color.Snot,
  TealGreen: Color.TealGreen,
  Transparent: Color.Transparent,
  UglyYellow: Color.UglyYellow,
  VeryLightPink: Color.VeryLightPink,
  VeryLightPinkFour: Color.VeryLightPinkFour,
  VeryLightPinkSeven: Color.VeryLightPinkSeven,
  VeryLightPinkSix: Color.VeryLightPinkSix,
  VeryLightPinkTwo: Color.VeryLightPinkTwo,
  VomitGreen: Color.VomitGreen,
  White: Color.White,
  White2: Color.White2,
  White3: Color.White3,
  WhiteTransparent: Color.WhiteTransparent,
  Yellow: Color.Yellow,
};

export const UnderlayPalette = {
  OrangeUnderlay: 'rgba(225, 148, 13,0.7)',
};

export function whiteTranslucent(opacity: number): string {
  checkOpacityValue(opacity);
  return `rgba(255, 255, 255, ${opacity})`;
}

export function grayTranslucent(opacity: number): string {
  checkOpacityValue(opacity);
  return `rgba(240, 240, 240, ${opacity})`;
}

export function redTranslucent(opacity: number): string {
  checkOpacityValue(opacity);
  return `rgba(210, 48, 48, ${opacity})`;
}

export function blackTranslucent(opacity: number): string {
  checkOpacityValue(opacity);
  return `rgba(0, 0, 0, ${opacity})`;
}

function checkOpacityValue(opacity: number) {
  if (opacity < 0 || opacity > 1) {
    throw new Error(`opacity must between 0 and 1, got ${opacity}`);
  }
}
