import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
  en: {
    alreadyhaveAnAccount: 'Already have an account?',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    passwordRepeatLabel: 'Password Repeat',
    login: 'Login',
    signUp: 'SignUp',
    signUpText: 'SignUp...',
    nameLabel: 'Name',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    ong: 'ONG',
    person: 'Person',
  },
  es: {
    alreadyhaveAnAccount: 'Ya tienes una cuenta?',
    emailLabel: 'Email',
    passwordLabel: 'Contraseña',
    passwordRepeatLabel: 'Contraseña Nuevamente',
    login: 'Loguearse',
    signUp: 'Registrarse',
    signUpText: 'Registrate...',
    nameLabel: 'Nombre',
    male: 'Masculino',
    female: 'Femenino',
    other: 'Otro',
    ong: 'ONG',
    person: 'Persona',
  },
  fr: {
    alreadyhaveAnAccount: 'Already have an account?',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    passwordRepeatLabel: 'Password Repeat',
    login: 'Login',
    signUp: 'SignUp',
    signUpText: 'SignUp...',
    nameLabel: 'Name',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    ong: 'ONG',
    person: 'Person',
  },
});
